# Github workflow for Continuous Integration

name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build the package
        run: npm run build

      - name: Run tests with code coverage
        run: npm run coverage

      - name: Send code coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
