# Github workflow to deploy the documentation to Github Pages

name: Deploy docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build docs bundle
        run: npm run docs

      - name: Deploy the documentation
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          BASE_BRANCH: master
          BRANCH: docs
          FOLDER: docs/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
